// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	model "github.com/SoulHardd/service-courier/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockdeliveryUseCase is a mock of deliveryUseCase interface.
type MockdeliveryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryUseCaseMockRecorder
}

// MockdeliveryUseCaseMockRecorder is the mock recorder for MockdeliveryUseCase.
type MockdeliveryUseCaseMockRecorder struct {
	mock *MockdeliveryUseCase
}

// NewMockdeliveryUseCase creates a new mock instance.
func NewMockdeliveryUseCase(ctrl *gomock.Controller) *MockdeliveryUseCase {
	mock := &MockdeliveryUseCase{ctrl: ctrl}
	mock.recorder = &MockdeliveryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryUseCase) EXPECT() *MockdeliveryUseCaseMockRecorder {
	return m.recorder
}

// AssignDelivery mocks base method.
func (m *MockdeliveryUseCase) AssignDelivery(ctx context.Context, orderId string) (*model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDelivery", ctx, orderId)
	ret0, _ := ret[0].(*model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignDelivery indicates an expected call of AssignDelivery.
func (mr *MockdeliveryUseCaseMockRecorder) AssignDelivery(ctx, orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDelivery", reflect.TypeOf((*MockdeliveryUseCase)(nil).AssignDelivery), ctx, orderId)
}

// UnassignDelivery mocks base method.
func (m *MockdeliveryUseCase) UnassignDelivery(ctx context.Context, orderId string) (*model.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignDelivery", ctx, orderId)
	ret0, _ := ret[0].(*model.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignDelivery indicates an expected call of UnassignDelivery.
func (mr *MockdeliveryUseCaseMockRecorder) UnassignDelivery(ctx, orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignDelivery", reflect.TypeOf((*MockdeliveryUseCase)(nil).UnassignDelivery), ctx, orderId)
}
