// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package usecase is a generated GoMock package.
package usecase

import (
	model "avito/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockcourierUseCase is a mock of courierUseCase interface.
type MockcourierUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockcourierUseCaseMockRecorder
}

// MockcourierUseCaseMockRecorder is the mock recorder for MockcourierUseCase.
type MockcourierUseCaseMockRecorder struct {
	mock *MockcourierUseCase
}

// NewMockcourierUseCase creates a new mock instance.
func NewMockcourierUseCase(ctrl *gomock.Controller) *MockcourierUseCase {
	mock := &MockcourierUseCase{ctrl: ctrl}
	mock.recorder = &MockcourierUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierUseCase) EXPECT() *MockcourierUseCaseMockRecorder {
	return m.recorder
}

// CreateCourier mocks base method.
func (m *MockcourierUseCase) CreateCourier(ctx context.Context, req *model.Courier) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourier", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourier indicates an expected call of CreateCourier.
func (mr *MockcourierUseCaseMockRecorder) CreateCourier(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourier", reflect.TypeOf((*MockcourierUseCase)(nil).CreateCourier), ctx, req)
}

// GetCourier mocks base method.
func (m *MockcourierUseCase) GetCourier(ctx context.Context, id int64) (*model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourier", ctx, id)
	ret0, _ := ret[0].(*model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourier indicates an expected call of GetCourier.
func (mr *MockcourierUseCaseMockRecorder) GetCourier(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourier", reflect.TypeOf((*MockcourierUseCase)(nil).GetCourier), ctx, id)
}

// GetCouriers mocks base method.
func (m *MockcourierUseCase) GetCouriers(ctx context.Context) ([]model.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCouriers", ctx)
	ret0, _ := ret[0].([]model.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCouriers indicates an expected call of GetCouriers.
func (mr *MockcourierUseCaseMockRecorder) GetCouriers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCouriers", reflect.TypeOf((*MockcourierUseCase)(nil).GetCouriers), ctx)
}

// UpdateCourier mocks base method.
func (m *MockcourierUseCase) UpdateCourier(ctx context.Context, req *model.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCourier", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCourier indicates an expected call of UpdateCourier.
func (mr *MockcourierUseCaseMockRecorder) UpdateCourier(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCourier", reflect.TypeOf((*MockcourierUseCase)(nil).UpdateCourier), ctx, req)
}
