// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	domain "github.com/SoulHardd/service-courier/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCourierRepository is a mock of CourierRepository interface.
type MockCourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourierRepositoryMockRecorder
}

// MockCourierRepositoryMockRecorder is the mock recorder for MockCourierRepository.
type MockCourierRepositoryMockRecorder struct {
	mock *MockCourierRepository
}

// NewMockCourierRepository creates a new mock instance.
func NewMockCourierRepository(ctrl *gomock.Controller) *MockCourierRepository {
	mock := &MockCourierRepository{ctrl: ctrl}
	mock.recorder = &MockCourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourierRepository) EXPECT() *MockCourierRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCourierRepository) Create(ctx context.Context, courier *domain.Courier) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, courier)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCourierRepositoryMockRecorder) Create(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCourierRepository)(nil).Create), ctx, courier)
}

// GetAll mocks base method.
func (m *MockCourierRepository) GetAll(ctx context.Context) ([]domain.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]domain.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCourierRepositoryMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCourierRepository)(nil).GetAll), ctx)
}

// GetOneById mocks base method.
func (m *MockCourierRepository) GetOneById(ctx context.Context, id int64) (*domain.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneById", ctx, id)
	ret0, _ := ret[0].(*domain.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneById indicates an expected call of GetOneById.
func (mr *MockCourierRepositoryMockRecorder) GetOneById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneById", reflect.TypeOf((*MockCourierRepository)(nil).GetOneById), ctx, id)
}

// GetOneForDelivery mocks base method.
func (m *MockCourierRepository) GetOneForDelivery(ctx context.Context) (*domain.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneForDelivery", ctx)
	ret0, _ := ret[0].(*domain.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneForDelivery indicates an expected call of GetOneForDelivery.
func (mr *MockCourierRepositoryMockRecorder) GetOneForDelivery(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneForDelivery", reflect.TypeOf((*MockCourierRepository)(nil).GetOneForDelivery), ctx)
}

// ReleaseOneByOrderId mocks base method.
func (m *MockCourierRepository) ReleaseOneByOrderId(ctx context.Context, orderId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseOneByOrderId", ctx, orderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseOneByOrderId indicates an expected call of ReleaseOneByOrderId.
func (mr *MockCourierRepositoryMockRecorder) ReleaseOneByOrderId(ctx, orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseOneByOrderId", reflect.TypeOf((*MockCourierRepository)(nil).ReleaseOneByOrderId), ctx, orderId)
}

// Update mocks base method.
func (m *MockCourierRepository) Update(ctx context.Context, courier *domain.Courier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, courier)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCourierRepositoryMockRecorder) Update(ctx, courier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCourierRepository)(nil).Update), ctx, courier)
}
