// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	"github.com/SoulHardd/service-courier/internal/domain"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockDeliveryRepository is a mock of DeliveryRepository interface.
type MockDeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryRepositoryMockRecorder
}

// MockDeliveryRepositoryMockRecorder is the mock recorder for MockDeliveryRepository.
type MockDeliveryRepositoryMockRecorder struct {
	mock *MockDeliveryRepository
}

// NewMockDeliveryRepository creates a new mock instance.
func NewMockDeliveryRepository(ctrl *gomock.Controller) *MockDeliveryRepository {
	mock := &MockDeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockDeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryRepository) EXPECT() *MockDeliveryRepositoryMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockDeliveryRepository) Assign(ctx context.Context, orderId string, c *domain.Courier, deadline time.Time) (*domain.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, orderId, c, deadline)
	ret0, _ := ret[0].(*domain.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assign indicates an expected call of Assign.
func (mr *MockDeliveryRepositoryMockRecorder) Assign(ctx, orderId, c, deadline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockDeliveryRepository)(nil).Assign), ctx, orderId, c, deadline)
}

// ReleaseExpireDeliveries mocks base method.
func (m *MockDeliveryRepository) ReleaseExpireDeliveries(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseExpireDeliveries", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseExpireDeliveries indicates an expected call of ReleaseExpireDeliveries.
func (mr *MockDeliveryRepositoryMockRecorder) ReleaseExpireDeliveries(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseExpireDeliveries", reflect.TypeOf((*MockDeliveryRepository)(nil).ReleaseExpireDeliveries), ctx)
}

// Unassign mocks base method.
func (m *MockDeliveryRepository) Unassign(ctx context.Context, orderId string) (*domain.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign", ctx, orderId)
	ret0, _ := ret[0].(*domain.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unassign indicates an expected call of Unassign.
func (mr *MockDeliveryRepositoryMockRecorder) Unassign(ctx, orderId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockDeliveryRepository)(nil).Unassign), ctx, orderId)
}
